apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce # Same as PV
  resources:
    requests:
      storage: 1Gi # Must match the storage available in PV
