apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-app-config
data:
  server.js: |
    const express = require('express');
    const app = express();
    const promClient = require('prom-client');
    const collectDefaultMetrics = promClient.collectDefaultMetrics;
    collectDefaultMetrics();
    const httpRequestDurationMicroseconds = new promClient.Histogram({
      name: 'http_request_duration_seconds',
      help: 'Duration of HTTP requests in seconds',
      labelNames: ['method', 'route', 'code'],
    });
    app.use((req, res, next) => {
      const end = httpRequestDurationMicroseconds.startTimer();
      res.on('finish', () => {
        end({ route: req.route ? req.route.path : req.url, method: req.method, code: res.statusCode });
      });
      next();
    });
    app.get('/', (req, res) => res.send('Hello World!'));
    app.get('/metrics', async (req, res) => {
      res.set('Content-Type', promClient.register.contentType);
      res.end(await promClient.register.metrics());
    });
    const port = 3000;
    app.listen(port, () => console.log(`Server listening on port ${port}`));
