apiVersion: v1
kind: Pod
metadata:
  name: secret-app-pod
spec:
  containers:
  - name: secret-app-container
    image: nginx
    env:s
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret  # The name of the Secret
          key: username    # The key within the Secret
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  restartPolicy: Never
