Step 1: Create Pod with Secret as a Volume
Here's an example where the Secret is mounted as a volume:
apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: secret-volume-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"  # Path where the secret will be mounted
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret  # Refers to the Secret object
  restartPolicy: Never
