kubectl create secret generic my-secret --from-literal=username=myuser --from-literal=password=mypassword

apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: secret-container
    image: busybox
    command: [ "sh", "-c", "echo The secret is $USERNAME and $PASSWORD; sleep 3600" ]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
