#below is encoding
echo -n 'admin' | base64
echo -n 'password123' | base64
kubectl exec -it secret-app-pod -- /bin/sh
echo $USERNAME
echo $PASSWORD

========================
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=       # base64-encoded 'admin'
  password: cGFzc3dvcmQxMjM=  # base64-encoded 'password123'
